FROM python:3.8.5-alpine
COPY requirements.txt requirements.txt
COPY Scrapper.py Scrapper.py
COPY ticker.csv ticker.csv
RUN pip install -r requirements.txt
ENTRYPOINT ["python","Sracpper.py", "./ticker.csv"]