FROM python:3.8.5
COPY requirements.txt requirements.txt
COPY Scapper.py Scrapper.py
COPY Server.py Server.py
COPY ticker.csv ticker.csv
RUN pip install -r requirements.txt --trusted-host pypi.python.org
ENTRYPOINT ["python","Server.py", "./ticker.csv"]
